### ISSUE TITLE
Error while running user accounts query

### ISSUE THREAD

**Issue by wolfieorama** [ankane/blazer#52] opened 2016-03-09 12:28 UTC
Hi, I am running blazer BI and all queries are running except when i want to pull user accounts data i get an `internal server error` here is the log 

```
Blazer::Check Load (0.3ms)  SELECT "blazer_checks".* FROM "blazer_checks" WHERE "blazer_checks"."query_id" = $1  [["query_id", 17]]
  Rendered /home/jmunyi/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/blazer-1.1.0/app/views/blazer/queries/run.html.erb (4.3ms)
Completed 500 Internal Server Error in 416ms (ActiveRecord: 259.7ms)

ActionView::Template::Error (invalid address):
     98:                     <% end %>
     99: 
    100:                     <% unless v.nil? %>
    101:                       <% if v == "" %>
    102:                         <div class="text-muted">empty string</div>
    103:                       <% elsif @linked_columns[k] %>
    104:                         <%= link_to blazer_format_value(k, v), @linked_columns[k].gsub("{value}", u(v.to_s)), target: "_blank" %>

```

the query is a very basic ans simple one 

`SELECT * FROM users WHERE team_id = {team_id}`

any ideas

**Comment by ankane** [comment] 2016-03-23 03:10
Hi @wolfieorama, this can happen if a linked column generates a bad path / url.

**Comment by jamarat** [comment] 2016-04-08 09:58
Hi, I also encountered the same error. It looks like there is a problem with rendering ip address column (in my case it is ordinary Devise's users table) when there is invalid ip address stored (see stacktrace below). In my table the value is either null or "::1". I don't know why it is "::1" but I don't care.

I can reproduce this error with: 
```
SELECT current_sign_in_ip
FROM users 
WHERE current_sign_in_ip is not null 
```
In my case it has nothing to do with a linked column url.
Anyway, good job!
Jakub

Stacktrace:
```
Completed 500 Internal Server Error in 13ms (ActiveRecord: 2.1ms)

IPAddr::InvalidAddressError - invalid address:
  /Users/me/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/ipaddr.rb:559:in `in6_addr'
  /Users/me/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/ipaddr.rb:496:in `initialize'
  /Users/me/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/ipaddr.rb:514:in `coerce_other'
  /Users/me/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/ipaddr.rb:150:in `=='
  blazer (1.2.0) app/views/blazer/queries/run.html.erb:105:in `block (2 levels) in ___sers_me__rvm_gems_ruby_______myapp_gems_blazer_______app_views_blazer_queries_run_html_erb___2738662801937125238_70201593637100'
  blazer (1.2.0) app/views/blazer/queries/run.html.erb:98:in `block in ___sers_me__rvm_gems_ruby_______myapp_gems_blazer_______app_views_blazer_queries_run_html_erb___2738662801937125238_70201593637100'
  blazer (1.2.0) app/views/blazer/queries/run.html.erb:96:in `___sers_me__rvm_gems_ruby_______myapp_gems_blazer_______app_views_blazer_queries_run_html_erb___2738662801937125238_70201593637100'
  actionview (4.2.5.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.5.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5.1) lib/abstract_controller/rendering.rb:25:in `render'
  ...(removed)
```

**Comment by ankane** [comment] 2016-05-03 07:02
Thanks for getting to the root cause @jamarat! Fixed on master.

**Closed** 2016-05-03 07:01 UTC
